# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** [Bonaventura Isaac Guric]
- **Email:** [bonaventuraisaac52@gmail.com]
- **ID Dicoding:** [bonaventuraisaac]

## Menentukan Pertanyaan Bisnis

- Bagaimana pengaruh musim terhadap jumlah peminjaman sepeda?
- Pada bulan apa terjadi peningkatan jumlah peminjaman sepeda?
- Apakah ada perbedaan pola pengguna casual dan pengguna terdaftar dalam penggunaan sepeda pada hari libur?

## Import Semua Packages/Library yang Digunakan
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import io

"""## Data Wrangling

### Gathering Data
""" 

df_day = pd.read_csv('https://raw.githubusercontent.com/tukangtukangtukang/FinalProyekAnalisisData/main/day.csv')
df_hour = pd.read_csv('https://raw.githubusercontent.com/tukangtukangtukang/FinalProyekAnalisisData/main/hour.csv')
st.write(df_day.head())
st.write(df_hour.head())

"""**Insight:**
- Data yang digunakan terdiri dari dua file yaitu `day.csv` dan `hour.csv`.
- Masing-masing dataset terdiri dari beberapa kolom yang berisi informasi terkait penggunaan sepeda seperti tanggal, temperature, hari, pengguna, dll.

### Assessing Data
"""

buffer_day = io.StringIO()
df_day.info(buf=buffer_day)
info_day = buffer_day.getvalue()

buffer_hour = io.StringIO()
df_hour.info(buf=buffer_hour)
info_hour = buffer_hour.getvalue()

st.subheader('Info Dataset Day')
st.text(info_day)
st.subheader('Info Dataset Hour')
st.text(info_hour)

st.subheader('Duplikasi dan Missing Value')
jumlah_duplikasi_day = df_day.duplicated().sum()
jumlah_duplikasi_hour = df_hour.duplicated().sum()

st.write("Jumlah duplikasi pada dataframe `df_day`: ", jumlah_duplikasi_day)
st.write("Jumlah duplikasi pada dataframe `df_hour`:  ", jumlah_duplikasi_hour)

st.write(df_day.describe())
st.write(df_hour.describe())

"""**Insight:**
- Pada dataframe `df_day` dan `df_hour` yang ternyata sudah bersih sehingga tidak terdapat missing value, data duplikat, maupun inaccurate value.
- Pada dataframe `df_day` dan `df_hour` terdapat kolom `dteday` yang bertipe data `object` yang perlu diubah menjadi `datetime` agar lebih akurat.

### Cleaning Data
"""

st.subheader('Mengubah Tipe Data `dteday`')
st.write(df_day.columns)

dteday_columns = ["dteday"]
 
for column in dteday_columns:
  df_day[column] = pd.to_datetime(df_day[column])

for column in dteday_columns:
  df_hour[column] = pd.to_datetime(df_hour[column])

buffer_day = io.StringIO()
df_day.info(buf=buffer_day)
info_day = buffer_day.getvalue()

buffer_hour = io.StringIO()
df_hour.info(buf=buffer_hour)
info_hour = buffer_hour.getvalue()

st.text(info_day)
st.text(info_hour)

st.subheader('Mengubah Kolom `season`')
# Mapping angka menjadi kategori musim
season_mapping = {
    1: 'Spring',
    2: 'Summer',
    3: 'Fall',
    4: 'Winter'
}

# Mengganti nilai kolom season di df_day dan df_hour
df_day['season'] = df_day['season'].replace(season_mapping)
df_hour['season'] = df_hour['season'].replace(season_mapping)

# Menampilkan 5 baris pertama dari dataset df_day
st.subheader('Data dari day.csv (Setelah Mengubah Kolom Season)')
st.write(df_day[['dteday', 'season']])

# Menampilkan 5 baris pertama dari dataset df_hour
st.subheader('Data dari hour.csv (Setelah Mengubah Kolom Season)')
st.write(df_hour[['dteday', 'season']])

"""**Insight:**
- Kolom dteday berhasil diubah menjadi format datetime, sehingga mempermudah proses pengelompokan data berdasarkan tanggal dan waktu.
- Kolom season yang sebelumnya berisi angka 1-4 diubah menjadi kategori seperti 'Spring', 'Summer', 'Fall', dan 'Winter' agar lebih mudah dipahami.


## Exploratory Data Analysis (EDA)

### Explore ...
"""

# 1. Pengaruh Musim terhadap Jumlah Peminjaman Sepeda
st.subheader('Pengaruh Musim terhadap Jumlah Peminjaman Sepeda')
season_analysis = df_day.groupby('season')['cnt'].sum().reset_index()
st.write(season_analysis)

# 2. Bulan dengan Peningkatan Jumlah Peminjaman
st.subheader('Jumlah Peminjaman Sepeda per Bulan')
monthly_analysis = df_day.groupby('mnth')['cnt'].sum().reset_index()
monthly_analysis['month_name'] = monthly_analysis['mnth'].apply(lambda x: pd.to_datetime(f'2011-{x}-01').strftime('%B'))
st.write(monthly_analysis[['month_name', 'cnt']])

# 3. Perbedaan Pola Pengguna Casual dan Terdaftar pada Hari Libur
st.subheader('Perbedaan Pola Pengguna Casual dan Terdaftar pada Hari Libur')
holiday_analysis = df_day[df_day['holiday'] == 1]
user_pattern = holiday_analysis[['casual', 'registered']].sum().reset_index()
user_pattern.columns = ['User Type', 'Total Count']  # Memberi nama kolom yang lebih jelas
st.write(user_pattern)

"""**Insight:**
- Musim Gugur mencatat jumlah peminjaman tertinggi dengan 1.061.129 peminjaman, menunjukkan bahwa pengguna sepeda lebih aktif saat cuaca cenderung nyaman dan stabil.
- Peningkatan peminjaman sepeda terjadi secara signifikan dari Maret hingga Agustus, dengan puncaknya mencapai 351.194 pada bulan Agustus, yang mengindikasikan minat pengguna terhadap aktivitas luar ruangan saat cuaca lebih baik.
- Pada hari libur, pengguna terdaftar (56.076) secara signifikan lebih banyak memanfaatkan layanan sepeda dibandingkan dengan pengguna kasual (22.359), menunjukkan bahwa layanan ini lebih banyak digunakan untuk keperluan komuter dibandingkan rekreasi.


## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""
st.subheader('Bagaimana pengaruh musim terhadap jumlah peminjaman sepeda?')
# Membaca dataset
df_day = pd.read_csv('https://raw.githubusercontent.com/tukangtukangtukang/FinalProyekAnalisisData/main/day.csv')

# Mengonversi kolom 'season' menjadi kategori yang lebih mudah dipahami
season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
df_day['season'] = df_day['season'].map(season_map)

# Menghitung total peminjaman sepeda per musim
seasonal_data = df_day.groupby('season')['cnt'].sum().reset_index()

# Menampilkan data seasonal_data untuk memastikan nilainya
st.write("Data peminjaman sepeda per musim:")
st.write(seasonal_data)

# Membuat visualisasi
fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(data=seasonal_data, x='season', y='cnt', ax=ax, palette='viridis', ci=None)
ax.set_title('Total Peminjaman Sepeda per Musim')
ax.set_xlabel('Musim')
ax.set_ylabel('Jumlah Peminjaman')
ax.grid()

# Menambahkan label nilai di atas setiap bar
for i, v in enumerate(seasonal_data['cnt']):
    ax.text(i, v, f'{v:,}', ha='center', va='bottom')

# Mengatur skala y-axis agar dimulai dari 0
ax.set_ylim(0, max(seasonal_data['cnt']) * 1.1)

# Menampilkan visualisasi di Streamlit
st.pyplot(fig)

"""### Pertanyaan 2:"""

st.subheader('Pada bulan apa terjadi peningkatan jumlah peminjaman sepeda?')
plt.figure(figsize=(10, 6))
sns.lineplot(data=monthly_analysis, x='month_name', y='cnt', marker='o', color='blue')
plt.title('Jumlah Peminjaman Sepeda per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Total Peminjaman')
plt.xticks(rotation=45)
st.pyplot(plt)


"""### Pertanyaan 3:"""

st.subheader('Apakah ada perbedaan pola pengguna casual dan pengguna terdaftar dalam penggunaan sepeda pada hari kerja / hari libur?')
fig, ax = plt.subplots(figsize=(10, 6))

# Menambahkan kolom baru 'type' untuk membedakan pengguna casual dan registered
hour_df_melt = df_hour.melt(id_vars=['workingday'], value_vars=['casual', 'registered'], 
                            var_name='user_type', value_name='count')

# Menggunakan dodge untuk memisahkan pengguna casual dan registered pada bar chart
sns.barplot(data=hour_df_melt, x='workingday', y='count', hue='user_type', ax=ax, dodge=True)
ax.set_title('Penggunaan Sepeda Berdasarkan Hari Libur / Hari Kerja')
ax.set_xlabel('0: Akhir Pekan/Hari Libur, 1: Hari Kerja')
ax.set_ylabel('Jumlah Peminjaman')
ax.legend(title='Tipe Pengguna')
ax.grid()
st.pyplot(fig) 



"""**Insight:**
- Pada pertanyaan 1, musim gugur adalah periode dengan jumlah peminjaman tertinggi, diikuti oleh musim panas. Musim dingin dan musim semi menunjukkan angka yang lebih rendah, dengan musim semi mencatat jumlah peminjaman terendah. Hal ini menunjukkan bahwa pengguna sepeda lebih cenderung bersepeda dalam cuaca yang nyaman dan stabil.
- Pada pertanyaan 2, peningkatan jumlah peminjaman sepeda mulai terjadi pada bulan Maret dan mencapai puncaknya pada bulan Juli dan Agustus. Hal ini dapat dihubungkan dengan perubahan cuaca dan aktivitas luar ruangan yang meningkat pada periode tersebut.
- Pada pertanyaan 3, terlihat bahwa pengguna terdaftar (registered) secara konsisten menggunakan layanan sepeda lebih banyak daripada pengguna kasual (casual), dengan peningkatan signifikan pada hari kerja, menunjukkan bahwa layanan ini terutama dimanfaatkan untuk komuter harian, sementara pengguna kasual lebih cenderung menggunakannya untuk rekreasi di akhir pekan.
## Analisis Lanjutan (Opsional)
"""

# Memeriksa tipe data
st.write("Tipe Data dalam DataFrame:")
st.write(df_day.dtypes)

# Mengonversi kolom 'cnt', 'casual', dan 'registered' menjadi numerik
df_day['cnt'] = pd.to_numeric(df_day['cnt'], errors='coerce')
df_day['casual'] = pd.to_numeric(df_day['casual'], errors='coerce')
df_day['registered'] = pd.to_numeric(df_day['registered'], errors='coerce')

# Menghitung rata-rata jumlah peminjaman berdasarkan musim
grouped_data = df_day.groupby('season')['cnt'].mean().reset_index()

# Menampilkan hasil di Streamlit
st.write("Rata-rata Peminjaman Sepeda per Musim menggunakan Clustering:")
st.write(grouped_data)

"""## Conclusion

- Pertanyaan 1: Musim gugur mencatat jumlah peminjaman tertinggi dibandingkan musim lainnya, diikuti oleh musim panas. Sebaliknya, musim dingin dan musim semi menunjukkan angka yang lebih rendah, dengan musim semi mencatat jumlah peminjaman terendah. Hal ini menunjukkan bahwa pengguna sepeda lebih cenderung untuk bersepeda dalam cuaca yang nyaman dan stabil, di mana musim gugur dan musim panas memberikan kondisi yang lebih baik untuk aktivitas luar ruangan.
- Pertanyaan 2: Peningkatan jumlah peminjaman sepeda mulai terjadi pada bulan Maret, dengan puncaknya tercatat pada bulan Juli dan Agustus. Puncak peminjaman ini dapat dihubungkan dengan perubahan cuaca yang lebih baik dan meningkatnya aktivitas luar ruangan selama musim panas. Oleh karena itu, dapat disimpulkan bahwa faktor cuaca dan ketersediaan waktu luang berkontribusi signifikan terhadap peningkatan peminjaman sepeda.
- Pertanyaan 3:  Analisis menunjukkan bahwa pengguna terdaftar (registered) secara konsisten menggunakan layanan sepeda lebih banyak dibandingkan pengguna kasual (casual). Peningkatan penggunaan ini terlihat lebih signifikan pada hari kerja, yang mengindikasikan bahwa layanan sepeda ini terutama dimanfaatkan untuk keperluan komuter harian. Sebaliknya, pengguna kasual cenderung menggunakan layanan ini untuk rekreasi di akhir pekan. Hal ini menandakan bahwa pengguna terdaftar lebih bergantung pada sepeda sebagai alat transportasi sehari-hari.
"""